REPORT zabapgitdemo.

PARAMETERS: p_lang TYPE BU_LANGU_CORR DEFAULT sy-langu.

START-OF-SELECTION.
LOG-POINT ID ZABAPGITDEMO FIELDS p_lang.

WRITE: / 'Hello World'.

BREAK-POINT ID ZABAPGITDEMO.

ASSERT id ZABAPGITDEMO
FIELDS p_lang
CONDITION p_lang = 'E'.

WRITE: / p_lang.
